# Usar la imagen oficial de Node.js como imagen base
FROM node:20

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos del paquete.json y paquete-lock.json
COPY package*.json ./

# Instalar dependencias del proyecto
RUN npm install
RUN npm rebuild sqlite3

# Copiar todos los archivos del proyecto al directorio de trabajo
COPY . .

# Exponer el puerto que el servidor utilizará
EXPOSE 3000 50051

# Comando para ejecutar el servidor
CMD ["node", "src/index.js", "3000", "50051"]
