# Usar la imagen oficial de Node.js como imagen base
FROM node:20

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos del paquete.json y paquete-lock.json
COPY package*.json ./

# Instalar dependencias del proyecto
RUN npm install

# Copiar todos los archivos del proyecto al directorio de trabajo
COPY . .

# Exponer el puerto que el cliente podría usar (si es necesario)
EXPOSE 50051

# Comando para mantener el contenedor en ejecución, ajustar según sea necesario
CMD ["node", "src/index.js"]
